<span style="color:blue">Array Creation</span>

In [1]:
import numpy as np
y=np.array([1,5,7,9,11])
y

array([ 1,  5,  7,  9, 11])

In [2]:
y=np.array([[1,2,4,8,16],
            [3,5,7,9,15]])
y

array([[ 1,  2,  4,  8, 16],
       [ 3,  5,  7,  9, 15]])

In [3]:
x=np.array([ [1,2,8,5],
             [2,5,9,13],
             [4,2,9,8],
             [6,2,3,5] ])
print(x)

[[ 1  2  8  5]
 [ 2  5  9 13]
 [ 4  2  9  8]
 [ 6  2  3  5]]


In [75]:
#When the size of the lists inside array is different then it is recommended you specify dtype=object
c=np.array([ [1,2,8,5],
             [2,5,9,13,17],
             [4,2,9,8,19], 
             [6,2,8,3,5]])
c

C:\Users\ASUS\AppData\Local\Temp/ipykernel_31836/2119992822.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([ [1,2,8,5],


array([list([1, 2, 8, 5]), list([2, 5, 9, 13, 17]),
       list([4, 2, 9, 8, 19]), list([6, 2, 8, 3, 5])], dtype=object)

In [4]:
c=np.array([ [1,2,8,5],
             [2,5,9,13,17],
             [4,2,9,8,19], 
             [6,2,8,3,5]], dtype=object)
c

array([list([1, 2, 8, 5]), list([2, 5, 9, 13, 17]),
       list([4, 2, 9, 8, 19]), list([6, 2, 8, 3, 5])], dtype=object)

In [77]:
zeros=np.zeros((2,3))

another_zeros=np.zeros((15,7))
zeros, another_zeros

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]))

In [78]:
ones=np.ones((2,8))
another_ones=np.ones((5,12))
ones, another_ones

(array([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

<span style="color:blue">Array Generation Starts Below</span>

In [5]:
e=np.arange(15,200)
e

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
       184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 19

In [15]:
e=np.arange(-1,-50,-3)
e

array([ -1,  -4,  -7, -10, -13, -16, -19, -22, -25, -28, -31, -34, -37,
       -40, -43, -46, -49])

In [79]:
np.linspace(2,10,num=50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [83]:
np.logspace(1,3,num=5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

<span style="color:blue">Array Reshaping Starts Below</span>

In [86]:
x=np.arange(1,50,3.5)
x.shape=(2,7)
x

array([[ 1. ,  4.5,  8. , 11.5, 15. , 18.5, 22. ],
       [25.5, 29. , 32.5, 36. , 39.5, 43. , 46.5]])

In [94]:
x=np.arange(1,50,3.5)
y=x.reshape((2,7))
print(f"I am the original unchanged array {x}") 
print(f"I am the reshaped copy of original array \n{y}") 

I am the original unchanged array [ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5]
I am the reshaped copy of original array 
[[ 1.   4.5  8.  11.5 15.  18.5 22. ]
 [25.5 29.  32.5 36.  39.5 43.  46.5]]


In [100]:
import numpy as np
x=np.arange(2,32,3) # This contains 10 elements namely [2,5,8...29]
print("The original array is ",x)
print(x[2])

x=x.reshape(2,5) #(The product of 2 and 5 is 10 so it can be reshaped into 2 rows 5 columns)
print("The reshaped array is \n",x)

x=x.reshape(5,2)
print("The second reshaped is \n", x)

x=x.reshape(10,1)
print("The last combination is \n", x)

x=x.reshape(2,10)
print("The last combination is \n", x)

The original array is  [ 2  5  8 11 14 17 20 23 26 29]
8
The reshaped array is 
 [[ 2  5  8 11 14]
 [17 20 23 26 29]]
The second reshaped is 
 [[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]
 [26 29]]
The last combination is 
 [[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]
 [20]
 [23]
 [26]
 [29]]


ValueError: cannot reshape array of size 10 into shape (2,10)

<span style="color:blue">Array Slicing Starts Below</span>

In [99]:
x=np.arange(12)
print(x)
print(x[1:8:3])

y=np.arange(3,50,2)
print(y)
print(y[3:15:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 4 7]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[ 9 15 21 27]


<span style="color:blue">Array Indexing Starts Below</span>

In [117]:
# 1. Multi-dimensional slicing
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
multi_dim_slice = arr[1:2, 1:]

print("The original 2D array is \n", arr)
print("The slicing on 2D array is \n", multi_dim_slice)

The original 2D array is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The slicing on 2D array is 
 [[5 6]]


In [118]:
# 2. Boolean indexing
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
bool_indexing = arr[arr % 2 == 0]

bool_indexing

array([2, 4, 6, 8])

In [121]:
# 3. Fancy indexing
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
fancy_indexing = arr[[2, 0, 1], [1, 2, 0]]
fancy_indx = arr[[1,2,0], [0,2,2]]
fancy = arr[[2,1], [0,1]]

fancy_indexing, fancy_indx, fancy

(array([8, 3, 4]), array([4, 9, 3]), array([7, 5]))

In [125]:
#Integer Array Indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])

indices = np.array([1, 3, 4])
result = arr[indices]
print("1D integer array indexing is", result)

#Integer Array Indexing in 2D array
arr_2d = np.array([[1, 5, 3], 
                   [4, 7, 6], 
                   [13, 12, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = arr_2d[row_indices, col_indices]
print(f"The 2D integer array indexing is", result)

#Integer Array Indexing in 3D array
y=np.array([12,46,29,57,46,19,78,97,109,23,44,39])
y.shape=(3,2,2)

indices_dim0 = np.array([0, 2])
indices_dim1 = np.array([1, 0])
indices_dim2 = np.array([0, 1])

result = y[indices_dim0, indices_dim1, indices_dim2]
print(f"The 3D integer array indexing is", result)

1D integer array indexing is [20 40 50]
The 2D integer array indexing is [ 5  6 13]
The 3D integer array indexing is [29 23]


In [139]:
#Boolean Array Indexing
import numpy as np
x = np.arange(35).reshape(5, 7)
print("The 2D array is \n", x)
b = x > 20
print("The condition is \n", b)
b[:, 5] #-> [ : Represents rows and 5 represents column, so you're selecting all rows from 6th column (0th index) ]
print("Boolean Indexing #1 \n", x[b[:,5]])

#12.1) For 3D array 
y = np.array([12, 46, 29, 57, 46, 19, 78, 97, 109, 23, 44, 39])
y.shape = (3, 2, 2)
print("The 3D array is \n", y)
	
# Create a boolean array based on a condition
condition = y > 30
print("The conditions \n", condition)
	
# Use boolean array indexing to select elements
result = y[condition]
print("The final result \n", result)

The 2D array is 
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
The condition is 
 [[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
Boolean Indexing #1 
 [[21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
The 3D array is 
 [[[ 12  46]
  [ 29  57]]

 [[ 46  19]
  [ 78  97]]

 [[109  23]
  [ 44  39]]]
The conditions 
 [[[False  True]
  [False  True]]

 [[ True False]
  [ True  True]]

 [[ True False]
  [ True  True]]]
The final result 
 [ 46  57  46  78  97 109  44  39]


<span style="color:blue">Random Function Starts Below</span>

In [218]:
x=np.random.randint(4,51)
print(x)

y=np.random.randint(-256, 256)
print(y)

F=np.random.randint(1,101, size=(5,5))
F

50
-213


array([[ 4, 17, 69, 71, 71],
       [99, 58, 94, 63, 37],
       [58, 46, 85, 91, 69],
       [70, 38, 17, 47, 74],
       [66, 94, 18, 94,  9]])

In [150]:
x=np.random.randint(4,51, size=6)
print(x)

y=np.random.randint(-256, 256, size=10)
print(y)

[40 49 24 30  8  9]
[ 165  144 -210  201 -191 -163 -111 -155   93 -248]


In [155]:
import numpy as np
F=np.random.seed(40)
y=np.random.randint(4,51, size=6)
print(y) #-> The output would always be [10 31 11 41  5 16] for this seed value of 40.

Q=np.random.seed(82)
z=np.random.randint(4,51,size=10) #-> The output would always be [ 7  6  7 31 17 33] for the seed value of 82.
print(z)

[10 31 11 41  5 16]
[ 7  6  7 31 17 33 26 35 38 50]


<span style="color:blue">Data Types in Numpy Starts Below</span>

In [162]:
#Signed Integers
import numpy as np
data8=np.array([19,12,1,11,27,1,-131,130], dtype=np.int8)
print(data8)

data16=np.array([19,12,1,11,27,1,-131,34000], dtype=np.int16)
print(data16)

data32=np.array([19,12,1,11,27,1,-131,34000], dtype=np.int32)
print(data32)

[  19   12    1   11   27    1  125 -126]
[    19     12      1     11     27      1   -131 -31536]
[   19    12     1    11    27     1  -131 34000]


In [163]:
#Unsigned Integers
udata8=np.array([19,12,1,11,130,1,-131,-17], dtype=np.uint8)
print(udata8)

udata16=np.array([-14,-29,19,12,1,11,27,1,-131,-17], dtype=np.uint16)
print(udata16)

[ 19  12   1  11 130   1 125 239]
[65522 65507    19    12     1    11    27     1 65405 65519]


In [169]:
# NumPy floating points
float16_num = np.float16(-299.234)
float32_num = np.float32(-156.0234)
float64_num = np.float64(299.2345)

float16_num, float32_num, float64_num

(-299.2, -156.0234, 299.2345)

In [165]:
# NumPy complex numbers
complex64_num = np.complex64(1+2j)
complex128_num = np.complex128(1+2j)

complex64_num, complex128_num

((1+2j), (1+2j))

In [166]:
# Boolean types
bool_val = True  # Python's built-in bool type
np_bool_val = np.bool_(True)  # NumPy's bool type

np_bool_val

True

<span style="color:blue">String in Numpy Starts Below</span>

In [176]:
String=np.array(["AJ", "JA"])
string = np.array(["Ayush", "Akshay", 19, 28, "WWE"], dtype="object")
String, string

(array(['AJ', 'JA'], dtype='<U2'),
 array(['Ayush', 'Akshay', 19, 28, 'WWE'], dtype=object))

In [174]:
import numpy as np
s = 'Ayush'
n = 5
arr = np.array([s for _ in range(n)], dtype='object')
arr

array(['Ayush', 'Ayush', 'Ayush', 'Ayush', 'Ayush'], dtype=object)

<span style="color:blue">String Operations Numpy Starts Below</span>

In [193]:
String = np.array(["AYUSH", "ADITYA", "AKSHAY"])
strategic = np.array(["Israel", "Mossad", "Tel Aviv"])
lower = np.char.lower(String)
upper = np.char.upper(strategic)
length = np.char.str_len(strategic)
replace = np.char.replace(strategic, 'a', '@')
split = np.char.split(strategic)
join = np.char.join(['-'], strategic)
strip = np.char.strip(['Israel', "Mossad"], ' ')
concatenation = np.char.add(String, strategic)
contains = np.char.find(strategic, 'a') != -1

print("Upper Case:", upper)
print("Lower Case:", lower)
print("Lengths:", length)
print("Replaced:", replace)
print("Split:", split)
print("Joined:", join)
print("Stripped:", strip)
print("Concatenated:", concatenation)
print("Contains 'a':", contains)

Upper Case: ['ISRAEL' 'MOSSAD' 'TEL AVIV']
Lower Case: ['ayush' 'aditya' 'akshay']
Lengths: [6 6 8]
Replaced: ['Isr@el' 'Moss@d' 'Tel Aviv']
Split: [list(['Israel']) list(['Mossad']) list(['Tel', 'Aviv'])]
Joined: ['I-s-r-a-e-l' 'M-o-s-s-a-d' 'T-e-l- -A-v-i-v']
Stripped: ['Israel' 'Mossad']
Concatenated: ['AYUSHIsrael' 'ADITYAMossad' 'AKSHAYTel Aviv']
Contains 'a': [ True  True False]


In [191]:
strategic = np.array(["Israel", "Mossad", "Tel-Aviv"])
split = np.char.split(strategic, sep=" ")
split_second = np.char.split(strategic[2], sep="/")
split, split_second

(array([list(['Israel']), list(['Mossad']), list(['Tel-Aviv'])],
       dtype=object),
 array(list(['Tel-Aviv']), dtype=object))

In [192]:
strategic = np.array(["Israel", "Mossad", "Tel Aviv"])
replace = np.char.replace(strategic, 'a', '@')
print("Replaced:", replace)

Replaced: ['Isr@el' 'Moss@d' 'Tel Aviv']


In [194]:
strategic = np.array(["Israel", "Mossad", "Tel Aviv"])
contains = np.char.find(strategic, 'a') != -1
print("Contains 'a':", contains)

Contains 'a': [ True  True False]


<span style="color:blue">Date and Time in Numpy Starts Below</span>

In [219]:
# Create an array with a single date
date_array = np.array('2024-04-08', dtype='datetime64')

# Create a datetime64 object from a string
dt_64 = np.datetime64('2022-05-01')
print(dt64)  # Output: numpy.datetime64('2022-05-01')

# Create a datetime64 object from an integer (19821 days since 1970-01-01)
daty = np.datetime64(19821, 'D') #You can pass any number of days (20000, 'D') it will calculate from 1970-01-01
print(dt64)  # Output: numpy.datetime64('2024-04-08')

# Create a datetime64 object from an integer (21000 hours since 1970-01-01)
dati = np.datetime64(21000, 'h')
print(dt64)  # Output: numpy.datetime64('1972-05-25T00')

# Create an array of dates
dates = np.array(['2024-04-08', '2024-04-09', '2024-04-10'], dtype='datetime64')

date_array, dt_64, daty, dati, dates

1972-05-25T00
1972-05-25T00
1972-05-25T00


(array('2024-04-08', dtype='datetime64[D]'),
 numpy.datetime64('2022-05-01'),
 numpy.datetime64('2024-04-08'),
 numpy.datetime64('1972-05-25T00','h'),
 array(['2024-04-08', '2024-04-09', '2024-04-10'], dtype='datetime64[D]'))

In [220]:
current_datetime = np.datetime64('now')
current_date = np.datetime64('today', 'D')
current_datetime, current_date

(numpy.datetime64('2024-04-09T07:11:23'), numpy.datetime64('2024-04-09'))

In [196]:
# Subtracting dates to get the number of days between them
diff = np.array('2024-04-10', dtype='datetime64') - np.array('2024-04-08', dtype='datetime64')

# Adding days to a date
new_date = np.array('2024-04-08', dtype='datetime64') + np.array(10, dtype='timedelta64[D]')

# Creating a range of dates
date_range = np.arange('2024-04-08', '2024-04-15', dtype='datetime64[D]')

diff, new_date, date_range

(numpy.timedelta64(2,'D'),
 numpy.datetime64('2024-04-18'),
 array(['2024-04-08', '2024-04-09', '2024-04-10', '2024-04-11',
        '2024-04-12', '2024-04-13', '2024-04-14'], dtype='datetime64[D]'))

In [216]:
# Subtract two datetime64 objects to get a timedelta64
dt1 = np.datetime64('2022-05-01')
dt2 = np.datetime64('2022-01-01')
delta = dt1 - dt2
print(delta)  # Output: numpy.timedelta64(121,'D')

# Add a timedelta64 to a datetime64
new_dt = dt1 + np.timedelta64(10, 'D')
print(new_dt)  # Output: numpy.datetime64('2022-05-11')

new_date = np.array('2024-04-08', dtype='datetime64') + np.array(100, dtype='timedelta64[h]')
print(new_date)

120 days
2022-05-11
2024-04-12T04


In [ ]:
import numpy as np
s = ''
n = 5
arr = np.array([s for _ in range(n)], dtype='object')

<span style="color:blue">Array Manipulation : Flattening Array Starts Below</span>

In [221]:
import numpy as np
A=np.arange(20).reshape(5,4)
B=A.flatten()
print("The flattened 1D array is\n", B)
B[3]=8576 #Changes doesn't affect original array
print("The final 1D array after flatten() is\n", A)

D=np.arange(20).reshape(5,4)
E=D.ravel()
print("The 1D array is\n", E)
E[3]=8576 #Changes affect original array
print("The final 1D array after ravel() is\n", D)

The flattened 1D array is
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The final 1D array after flatten() is
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The 1D array is
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The final 1D array after ravel() is
 [[   0    1    2 8576]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]]


<span style="color:blue">Broadcasting Starts Below</span>

In [244]:
A=np.arange(1,60,4).reshape(3,5)
print(A)

value=10
print("The scalar valued added \n",A+value)

C = [[1],
     [2],
     [3],
     [4]]

D = [[1, 2, 3]]
print("The broadcasting \n", C+D)

[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]]
The scalar valued added 
 [[11 15 19 23 27]
 [31 35 39 43 47]
 [51 55 59 63 67]]
The broadcasting 
 [[1], [2], [3], [4], [1, 2, 3]]


In [286]:
A=np.arange(1,25).reshape(3,8)
B=np.arange(100,124).reshape(3,8)
print(A)
print(B)
print("Addition:\n",A+B)
print("Subtraction:\n",A-B)
print("Multiplication:\n",A*B)
print("Division:\n",A/B)
print("Standard Deviation", np.std(A+B))
print("Mean", np.mean(A+B))
print("Variance", np.var(A+B))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115]
 [116 117 118 119 120 121 122 123]]
Addition:
 [[101 103 105 107 109 111 113 115]
 [117 119 121 123 125 127 129 131]
 [133 135 137 139 141 143 145 147]]
Subtraction:
 [[-99 -99 -99 -99 -99 -99 -99 -99]
 [-99 -99 -99 -99 -99 -99 -99 -99]
 [-99 -99 -99 -99 -99 -99 -99 -99]]
Multiplication:
 [[ 100  202  306  412  520  630  742  856]
 [ 972 1090 1210 1332 1456 1582 1710 1840]
 [1972 2106 2242 2380 2520 2662 2806 2952]]
Division:
 [[0.01       0.01980198 0.02941176 0.03883495 0.04807692 0.05714286
  0.06603774 0.07476636]
 [0.08333333 0.09174312 0.1        0.10810811 0.11607143 0.12389381
  0.13157895 0.13913043]
 [0.14655172 0.15384615 0.16101695 0.16806723 0.175      0.18181818
  0.18852459 0.19512195]]
Standard Deviation 13.844373104863458
Mean 124.0
Variance 191.66666666666666


In [276]:
A=np.arange(1,25).reshape(3,8)
B=np.arange(1,4).reshape(3,1)
print(A)
print(B)
print(A+B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[1]
 [2]
 [3]]
[[ 2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18]
 [20 21 22 23 24 25 26 27]]


In [271]:
A=np.arange(1,25).reshape(3,8)

B=np.arange(2,10)

print("The size of A:",A.size)
print("The size of B:",B.size)
print("\t")
print("The array A is\n", A)
print("\t")
print("The array B is\n", B)
print("\t")
print("The broadcasting is\n",A+B)

The size of A: 24
The size of B: 8
	
The array A is
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
	
The array B is
 [2 3 4 5 6 7 8 9]
	
The broadcasting is
 [[ 3  5  7  9 11 13 15 17]
 [11 13 15 17 19 21 23 25]
 [19 21 23 25 27 29 31 33]]


In [280]:
#Aggregation along an axis in broadcasting
A=np.arange(1,25).reshape(3,8)
B=np.arange(1,4).reshape(3,1)
print(A)
print(B)
print(A*B)
print(np.mean(A*B))
print(np.sum(A*B, axis=1)) #Sum along rows of A*B 1+2+3+4+5+6+7+8 = 36

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[1]
 [2]
 [3]]
[[ 1  2  3  4  5  6  7  8]
 [18 20 22 24 26 28 30 32]
 [51 54 57 60 63 66 69 72]]
30.333333333333332
[ 36 200 492]


In [279]:
#Logical Operation in Broadcasting
A=np.arange(1,25).reshape(3,8)
B=np.arange(1,4).reshape(3,1)
print(A)
print(B)
print(np.logical_and(A > 5, B < 100))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[1]
 [2]
 [3]]
[[False False False False False  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


In [289]:
#1D array conversion to column and row vectors
B=np.array([1, 2, 3])  #Shape is (3,)
column_vector = B[:, np.newaxis] 
print(column_vector) #Shape is now(3,1)

array_1d = np.array([1, 2, 3])  # shape is (3,)
row_vector  = array_1d[np.newaxis, :]  # shape is now (1, 3)
print(row_vector)

[[1]
 [2]
 [3]]
[[1 2 3]]


In [284]:
new_array = array_1d[:, None]  # Equivalent to array_1d[:, np.newaxis]

<span style="color:blue">Stacking Starts Below</span>

In [290]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.stack([a,b])
print("Joins the arrays on row \n", c)

d=np.stack([a,b], axis=1)
print("Joins the arrays based on columns \n ", d)

Joins the arrays on row 
 [[1 2 3]
 [4 5 6]]
Joins the arrays based on columns 
  [[1 4]
 [2 5]
 [3 6]]


In [296]:
a = np.array([[1,2,3], 
              [4,5,6]])

b = np.array([[7, 8, 9],
              [10,11,12]])

c=np.stack([a,b])
print("Row wise stack\n", c)
print("\t")
d=np.stack([a,b], axis=1)
print("Column wise stack\n", d)

Row wise stack
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
	
Column wise stack
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [299]:
a=np.array([1,2,3,10])
b=np.array([4,5,6])

c=np.stack([a,b])
print("Joins the arrays on row \n", c) #Gives error because shape should be same

ValueError: all input arrays must have the same shape

In [298]:
a=np.array([1,2,3,10])
b=np.array([4,5,6,20])

c=np.stack([a,b])
print("Joins the arrays on row \n", c)

d=np.array_split(c, 3, axis=0)
print(d)

print("\n")

e=np.split(c,2, axis=0)
print(e)

Joins the arrays on row 
 [[ 1  2  3 10]
 [ 4  5  6 20]]
[array([[ 1,  2,  3, 10]]), array([[ 4,  5,  6, 20]]), array([], shape=(0, 4), dtype=int32)]


[array([[ 1,  2,  3, 10]]), array([[ 4,  5,  6, 20]])]


In [300]:
a = np.array([[1,1], [3,4]])
b = np.array([[2,2,2,2], [5,6,7,8]])

c=np.hstack([a,b])
print(c)

[[1 1 2 2 2 2]
 [3 4 5 6 7 8]]


In [301]:
a = np.array([[1,1,1], [1,1,1]])
b = np.array([[2,2,2], [2,2,2], [2,2,2], [2,2,2]])

c=np.vstack([a,b])
print(c)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
# Views instead of copies
arr_slice = arr[0, :]
arr_slice[0] = 999
view_effect_on_original = arr

In [106]:
x=np.arange(100,1257,6)
x[4]

124

In [40]:
y=np.array([12,46,29,57,46,19,78,97,109,23,44,39])
y.shape=(3,2,2)
print(y)

[[[ 12  46]
  [ 29  57]]

 [[ 46  19]
  [ 78  97]]

 [[109  23]
  [ 44  39]]]


In [41]:
import numpy as np

# Define an array with 6 elements
y = np.array([1, 2, 3, 4, 5, 6])

# Use y.shape to change the shape of the array in place
y.shape = (2, 3)  # Change the shape to 2 rows and 3 columns
print("After y.shape = (2, 3):")
print(y)

# Now, let's use y.reshape to create a new array with a different shape
reshaped_y = y.reshape((3, 2))  # Create a new array with 3 rows and 2 columns
print("\nAfter y.reshape((3, 2)) (original y remains unchanged):")
print(reshaped_y)  # This will be the new reshaped array
print("\nOriginal y (still has the shape given by y.shape):")
print(y)  # The original y remains with the shape given by y.shape

After y.shape = (2, 3):
[[1 2 3]
 [4 5 6]]

After y.reshape((3, 2)) (original y remains unchanged):
[[1 2]
 [3 4]
 [5 6]]

Original y (still has the shape given by y.shape):
[[1 2 3]
 [4 5 6]]


In [42]:
x=np.arange(2,2000)
count=x.size
count

1998

In [52]:
a = np.array([[1,1,1], [1,1,1]])
b = np.array([[2,2,2], [2,2,2], [2,2,2], [2,2,2]])

c=np.vstack([a,b])
print(c)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [70]:
a=np.array([1,2,3,10])
b=np.array([4,5,6,20])

c=np.stack([a,b])
print("Joins the arrays on row \n", c)

d=np.array_split(c, 3, axis=0)
print(d)

print("\n")

e=np.split(c,2, axis=0)
print(e)

Joins the arrays on row 
 [[ 1  2  3 10]
 [ 4  5  6 20]]
[array([[ 1,  2,  3, 10]]), array([[ 4,  5,  6, 20]]), array([], shape=(0, 4), dtype=int32)]


[array([[ 1,  2,  3, 10]]), array([[ 4,  5,  6, 20]])]


In [72]:
# Define the custom add function
def add_custom(x, y):
    return x + y

# Vectorize it with np.frompyfunc
add_frompyfunc = np.frompyfunc(add_custom, 2, 1)

# Apply it to two arrays
result = add_frompyfunc(np.array([1, 2, 3]), np.array([4, 5, 6]))
result

array([5, 7, 9], dtype=object)

In [74]:
# Vectorize it with np.vectorize
add_vectorize = np.vectorize(add_custom)

# Apply it to two arrays
result = add_vectorize(np.array([1, 2, 3]), np.array([4, 5, 6]))
result
print(result.dtype)

int32


In [302]:
d=np.array ([ [24,56,71],                        
              [78,93,36],
              [1,11,2006] ])
maximum_cols=np.max(d, axis=0)
print("The max column is ", maximum_cols)
maximum_rows=np.max(d, axis=1)
print("The max row is ", maximum_rows)
minimum_cols=np.min(d, axis=0)
print("The min column is ", minimum_cols)
minimum_rows=np.min(d, axis=1)
print("The min column is ", minimum_rows)

The max column is  [  78   93 2006]
The max row is  [  71   93 2006]
The min column is  [ 1 11 36]
The min column is  [24 36  1]
